name: Test
on: push
jobs:
  test:
    name: Jest + ESLint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12]
      fail-fast: true
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Building project
        uses: ./.github/actions/setup
      - name: Run Jest
        run: yarn run jest:coverage
      - name: Run ESLint
        run: yarn run lint:errors

  happo:
    name: Happo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Building project
        uses: ./.github/actions/setup
      - name: Using previous SHA
        if: contains(github.event.before, '0000000000') == false
        run: echo ::set-env name=PREVIOUS_SHA::"${{ github.event.before }}"
      - name: Using master SHA because no previous SHA
        if: contains(github.event.before, '0000000000') == true
        run: echo ::set-env name=PREVIOUS_SHA::$(git merge-base origin/master HEAD)
      - name: Run Happo CI
        run: yarn run happo:ci
        env:
          HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
          HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
          CURRENT_SHA: ${{ github.event.after }}
          CHANGE_URL: ${{ github.event.head_commit.url }}
